{% set name = "cloud-sql-python-connector" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cloud-sql-python-connector-{{ version }}.tar.gz
  sha256: a75f4c4b0a3cddc48f4b64d1a5e367279883aff8f35ea6d9f6372542c5af22b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp
    - cryptography
    - google-api-python-client
    - pyopenssl
    - python >=3.6
    - requests

test:
  imports:
    - google
    - google.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector
  summary: The Cloud SQL Python Connector is a library that can be used alongside a database driver to allow users with sufficient permissions to connect to a Cloud SQL database without having to manually allowlist IPs or manage SSL certificates.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
